version: 2.1

commands:
  destroy-environment:
      description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
      parameters: 
          workflow_id:
              type: string
              default: "${CIRCLE_WORKFLOW_ID:0:7}"
      steps:
          - run:
                name: Destroy environments
                when: on_fail
                command: |
                    aws s3 rb s3://udapeople-<< parameters.workflow_id >> --force  
                    aws cloudformation delete-stack \
                        --stack-name "udapeople-backend-<< parameters.workflow_id >>"
                    aws cloudformation delete-stack \
                        --stack-name "udapeople-frontend-<< parameters.workflow_id >>"

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
            export SUCCESS=$(curl -H "token: gajdulj" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7})
            echo $CIRCLE_WORKFLOW_ID
            echo $SUCCESS
            if(( $SUCCESS==1 )); 
            then
            echo "reverting migrations..."
            cd ~/project/backend
            ls
            npm install
            npm run migrations:revert
            fi

### Build Phase###
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

### Test Phase###

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [frontend-build]
      # Test job code
      - run:
          name: Front-end test
          command: |
            cd frontend
            npm i
            npm build
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: frontend-test
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [backend-build]
      # Test job code
      - run:
          name: Back-end test
          command: |
            cd backend
            npm i
            npm build
            npm run test
      - save_cache:
          paths: [backend/node_modules]
          key: backend-test

### Analyse Phase###

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [frontend-test]
      # Test job code
      - run:
          name: Front-end scan
          command: |
            cd frontend
            npm i
            npm audit --audit-level=critical --force

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [backend-test]
      # Test job code
      - run:
          name: Back-end scan
          command: |
            cd backend
            npm i
            # npm update
            npm audit fix --audit-level=critical --force

### Infrastructure Phase###

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar
      - run: yum install -y gzip
      - attach_workspace:
          at: ~/
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --tags project="udapeopleBackend_${CIRCLE_WORKFLOW_ID:0:7}" \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  

      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project="udapeopleFrontend_${CIRCLE_WORKFLOW_ID:0:7}" \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  

      - run:
          name: Add back-end ip to ansible inventory. Getting it as an output from backend.yml script.
          command: |


            # Save the ip
            backendip=$(aws cloudformation \
              list-exports --query "Exports[?Name==\`backendIP\`].Value" \
              --no-paginate --output text)

            # Send to memstash
            curl -H "Content-Type: text/plain" -H "token: gajdulj" --request PUT --data "$backendip" https://api.memstash.io/values/ec2_back_ip_${CIRCLE_WORKFLOW_ID}
            echo "Adding to memstash:"
            echo "$backendip"
            echo "$backendip" >> .circleci/ansible/inventory.txt
            # Save the url
            export backendurl="http://${backendip}:3030"
            echo "$backendurl"
            curl -H "Content-Type: text/plain" -H "token: gajdulj" --request PUT --data "$backendurl" https://api.memstash.io/values/ec2_back_url_${CIRCLE_WORKFLOW_ID}

      - run:
          name: Ensure inventory saved
          command: |
            ls ~/
            cat .circleci/ansible/inventory.txt
      - persist_to_workspace:
          root: .circleci
          paths:
            - ansible/inventory.txt
      # Here's where you will add some code to rollback on failure
      - destroy-environment

  configure-infrastructure:
    docker:
      # Docker image here that supports Ansible
      - image: alpine:latest
    steps:
      - checkout
      # Add ssh keys with fingerprint
      - add_ssh_keys:
          fingerprints: ["da:95:0f:a4:4a:71:0e:d4:f4:33:89:5b:24:57:76:99"]
      # attach workspace
      - attach_workspace:
          at: ~/
      - run:
          name: Ensure inventory loaded
          command: |
            ls
            ls ~/
            pwd
            apk add curl
            cat ~/project/.circleci/ansible/inventory.txt
            export BACKEND_IP=$(curl -H "token: gajdulj" --request GET \
            https://api.memstash.io/values/ec2_back_ip_${CIRCLE_WORKFLOW_ID})
            echo "${BACKEND_IP}"  >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt

      - run:
          name: Install dependencies
          command: |
            apk add --update ansible && apk add openssh
            ls
      - run:
          name: Set global vars
          command: |
            echo ENVIRONMENT=production > "backend/.env"
            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
            echo NODE_ENV=production >> "backend/.env"
            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
      - run:
          name: Configure server
          command: |
            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/configure-server.yml
      
            # Here's where you will add some code to rollback on failure 
      - destroy-environment

  run-migrations:
    docker:
      - image: circleci/node:13.8.0
      # Docker image here that supports NodeJS
    steps:
      - checkout
      - run:
          name: Run migrations
          # no_output_timeout: 10m
          command: |
            cd backend
            npm install
            echo "running migrations"
            npm run migrations > migrations.txt
            cat migrations.txt
      - run:
          name: Send migration results to memstash
          command: |
            curl -H "Content-Type: text/plain" -H "token: gajdulj" --request PUT --data "1" \
             https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
     # Here's where you will add some code to rollback on failure   

  deploy-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - attach_workspace:
          at: ~/
      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(curl -H "token: gajdulj" --request GET \
            https://api.memstash.io/values/ec2_back_ip_${CIRCLE_WORKFLOW_ID})
            export API_URL="http://${BACKEND_IP}:3030"
            echo "${API_URL}"

            cd frontend
            echo "${API_URL}" > apiurl.txt
      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            export API_URL=$(cat apiurl.txt)
            npm install
            npm run build
            aws s3 sync dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: Echo S3 location (front-end)
          command: |
            echo "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
      - destroy-environment
      - revert-migrations      


  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
  # Make sure ubuntu is 20.04 in backend.yml or you will have issues with PM2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "da:95:0f:a4:4a:71:0e:d4:f4:33:89:5b:24:57:76:99"
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible tar gzip ansible nodejs npm curl
            pip install awscli
      - run:
          name: Deploy backend
          command: |
            export BACKEND_IP=$(curl -H "token: gajdulj" --request GET \
            https://api.memstash.io/values/ec2_back_ip_${CIRCLE_WORKFLOW_ID})

            echo "$BACKEND_IP"
            echo "$BACKEND_IP" >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
            [[ ! -d backend ]] && mkdir backend
            envfile="backend/.env"
            echo ENVIROMENT=production > $envfile
            echo TYPEORM_CONNECTION=postgres >> $envfile
            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> $envfile
            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> $envfile
            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> $envfile
            echo TYPEORM_HOST=$TYPEORM_HOST >> $envfile
            echo TYPEORM_PORT=$TYPEORM_PORT >> $envfile
            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> $envfile
            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> $envfile
            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> $envfile
            tar -cvf backend.tar backend
            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml
      # Here's where you will add some code to rollback on failure
      - destroy-environment
      - revert-migrations

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
      # Lightweight Docker image 
    steps:
      # Checkout code from git
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update curl nodejs npm
            pip install awscli
      - run:
          name: Backend smoke test.
          command: |
            export BACKEND_IP=$(curl -H "token: gajdulj" --request GET \
            https://api.memstash.io/values/ec2_back_ip_${CIRCLE_WORKFLOW_ID})
            echo $BACKEND_IP
            echo "http://$BACKEND_IP:3030/api/status"
            curl -vvv "http://$BACKEND_IP:3030/api/status"

      - run:
          name: Frontend smoke test.
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-eu-west-1.amazonaws.com"
            echo $URL
            if curl -s ${URL} | grep "Welcome"
            then
              return 0
            else
              return 1
            fi
      - destroy-environment
      - revert-migrations

  cloudfront-update:
    docker:
      - image: amazon/aws-cli
      # Docker image here that supports AWS CLI
    steps:
      - checkout
      # Checkout code from git
      - run:
          name: update
          command: |
            # your code here
            ls .
            ls ..
            OLD_CIRCLE_WORKFLOW_ID=$(aws cloudformation list-exports --query "Exports[?Name=='WorkflowID'].Value" --output text)
            echo OLD_CIRCLE_WORKFLOW_ID=${OLD_CIRCLE_WORKFLOW_ID:0:7}
            STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter UPDATE_COMPLETE CREATE_COMPLETE --output text)
            echo STACKS=${STACKS}
            echo "Update CloudFront"
            aws cloudformation deploy \
              --template-file .circleci/files/cloudfront.yml \
              --stack-name Udapeople-Cloudfront \
              --region ${AWS_DEFAULT_REGION} \
              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
            STACKS=$(aws cloudformation list-stacks --query "StackSummaries[*].StackName" --stack-status-filter UPDATE_COMPLETE CREATE_COMPLETE --output text)
            echo STACKS=${STACKS}
            if [ -n "${OLD_CIRCLE_WORKFLOW_ID:0:7}" ] && [[ "${STACKS[@]}" =~ "${OLD_CIRCLE_WORKFLOW_ID:0:7}" ]]
            then
              echo "deleting stacks of ${OLD_CIRCLE_WORKFLOW_ID:0:7}"
              aws s3 rm "s3://udapeople-${OLD_CIRCLE_WORKFLOW_ID:0:7}" --recursive
              aws cloudformation delete-stack --stack-name udapeople-backendStack-${OLD_CIRCLE_WORKFLOW_ID:0:7}
              aws cloudformation delete-stack --stack-name udapeople-frontendStack-${OLD_CIRCLE_WORKFLOW_ID:0:7}
            fi

      - destroy-environment
      - revert-migrations 

  cleanup:
    docker:
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - run:
          name: Get old stack workflow id from memstash, get list of stack from 
          command: |
            # Get old workflow id
            export OldWorkflowID=$(curl -H "token: gajdulj" --request GET \
            https://api.memstash.io/values/persist_workflow_id)

            # Get stack list
            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
            --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
            echo "Old id ${OldWorkflowID}"
            echo "New id ${CIRCLE_WORKFLOW_ID:0:7}"
            echo ${STACKS}
      - run:
            name: Save current workflow id to memstash
            command: |
                curl -H "Content-Type: text/plain" \
                -H "token: gajdulj" \
                --request PUT --data "${CIRCLE_WORKFLOW_ID:0:7}" \
                https://api.memstash.io/values/persist_workflow_id
      - run:
            name: Remove old stacks and files
            command: |
                if [ "${OldWorkflowID}" != "" ]
                  then
                      aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
                      aws cloudformation delete-stack \
                      --stack-name "backend-stack-${OldWorkflowID}"
                      aws cloudformation delete-stack \
                      --stack-name "frontend-stack-${OldWorkflowID}"
                  else
                      echo "This must be the first run, no old workflow id."  
                fi
      - destroy-environment
      - revert-migrations

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
            requires: [build-frontend]
      - test-backend:
            requires: [build-backend]
      - scan-frontend:
            requires: [test-frontend]
      - scan-backend:
            requires: [test-backend]
      - deploy-infrastructure:
            requires: [scan-frontend, scan-backend]
            filters:
                branches:
                  only:
                    - main
      - configure-infrastructure:
            requires: [deploy-infrastructure]
      - run-migrations:
            requires: [configure-infrastructure]
      - deploy-frontend:
            requires: [run-migrations]
      - deploy-backend:
            requires: [deploy-frontend]
      - smoke-test:
            requires: [deploy-backend]
      - cloudfront-update:
            requires: [smoke-test]
      - cleanup:
              requires: [cloudfront-update]